apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: vspheremgmt
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 10.196.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/16
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: ""
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vspheremgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: vspheremgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vspheremgmt-etcd
  kubernetesVersion: "1.24"
  managementCluster:
    name: vspheremgmt
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vspheremgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: vspheremgmt
spec:
  datacenter: ""
  insecure: false
  network: ""
  server: ""
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vspheremgmt-cp
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vspheremgmt
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vspheremgmt-etcd
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---

